CREATE TABLE IF NOT EXISTS `auto_message` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `guild_id` VARCHAR(22) NOT NULL,
    `message` TEXT NOT NULL,
    `channel` VARCHAR(22) NOT NULL,
    `time` VARCHAR(5) NOT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
