CREATE TABLE IF NOT EXISTS `bot_settings` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `guild_id` VARCHAR(22) NOT NULL UNIQUE,
    `message` VARCHAR(50) DEFAULT NULL,
    `channel` VARCHAR(22) DEFAULT NULL,
    `enabled` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;