CREATE TABLE IF NOT EXISTS auto_message (
    id INT NOT NULL AUTO_INCREMENT,
    guild_id VARCHAR(22) NOT NULL,
    message TEXT NOT NULL,
    channel VARCHAR(22) NOT NULL,
    time VARCHAR(5) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0),
    PRIMARY KEY (id)
);
