CREATE TABLE IF NOT EXISTS `user_action` (
    id SERIAL PRIMARY KEY,
    guildId VARCHAR(255) NOT NULL,
    userId VARCHAR(20) NOT NULL,
    action VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);